### ISSUE TITLE
concurrency issue

### ISSUE THREAD

**Issue by emad-elsaid** [kofalt/go-memoize#7]
running this test: https://github.com/emad-elsaid/go-memoize-t
multiple times with: 
```
go clean -testcache && go test . -race
```
Note: we have to clean the test cache for the successful attempt not to be cached for consecutive runs.

I get wrong result, the function is executed multiple times instead of one 
```
--- FAIL: TestConcurrency (0.52s)
    memoize_test.go:36: 
                Error Trace:    /code/go-memoize-t/memoize_test.go:36
                                                        /usr/lib/go/src/runtime/asm_amd64.s:1695
                Error:          Not equal: 
                                expected: 1
                                actual  : 2
                Test:           TestConcurrency
    memoize_test.go:36: 
                Error Trace:    /code/go-memoize-t/memoize_test.go:36
                                                        /usr/lib/go/src/runtime/asm_amd64.s:1695
                Error:          Not equal: 
                                expected: 1
                                actual  : 2
                Test:           TestConcurrency
```

**Comment by kofalt** [comment]
Hi, thanks for writing in.

One easy way to disable test caching is to specify a run count. From `go help test`:
```
To disable test caching, use any test flag or argument other than the cacheable flags.
The idiomatic way to disable test caching explicitly is to use -count=1.
```

I can reliably reproduce your result:
```sh
# go test -count 1 -race

# ...
Test:           TestConcurrency
# ...
Error:          Not equal:
                expected: 1
                actual  : 2
```

However, I do not consider this an error in the library.
What's going on here is that your memoized function is extremely fast - barely a few nanoseconds:

```go
package main

import (
    "sync"
    "testing"
)

func BenchmarkEmad(b *testing.B) {

    counters := map[string]int{}
    var l sync.Mutex

    inc := func(k string) (int, error) {
        l.Lock()
        defer l.Unlock()
        counters[k]++

        return counters[k], nil
    }

    for i := 0; i < b.N; i++ {
        inc("key1")
    }
}
```
```sh
# go test -bench=.

BenchmarkEmad-24        87842586                12.77 ns/op
```

The reason you're seeing your memoizer execute more than once, is that I perform a cache lookup separate from the singleflight-gated function call. This **does** prevent overlapping writes (some concurrent result A clobbering result B), but **does not** provide 100% guaranteed deduplication.

The reason for this design is performance & throughput. A function that only takes a few nanoseconds is generally going to be faster than the overhead of calling a memoizer in the first place. If we disable the noisy `assert.Equal` inside your for loop, we can observe:

1. The memoizer can be called 30,000 times in 20 milliseconds (10k goroutines * 3 string keys)
1. The memoizer was able to reduce those 30,000 concurrent calls to just 7, or a 0.02% "overhead"

```sh
# go test -v -count 10 -race

# ...
=== RUN   TestConcurrency
    memoize_test.go:55:
                Error:          Not equal:
                                expected: map[string]int{"key1":1, "key2":1, "key3":1}
                                actual  : map[string]int{"key1":2, "key2":2, "key3":3}
--- FAIL: TestConcurrency (0.02s)
```

The exact numbers will vary from run to run. It would be possible to guarantee 100% deduplication - always return 1,1,1 for your test - but in my opinion that would be a bad idea. Memoization is generally more useful for functions that take milliseconds or seconds. 

For example, if I add just 30ms to your func via `time.Sleep(30*time.Millisecond)`, the memoizer will consistently deduplicate 300,000 calls with no extras at all. This will vary from machine to machine & other factors.

```sh
# go test -v -count 10 -race

PASS
ok      github.com/emad-elsaid/go-memoize-t     2.551s
```

The upside here is that you can probably just use the memoizer and not worry about it.

I have a commit updating the readme on this topic, and [added unit tests](https://github.com/kofalt/go-memoize/commit/1ccbd90e16e78201753992dacefdd318988f4649#diff-06219c7b7756802608319a34e39badd7851beaf759b8d490174a4412684e2d2dR156) confirming that a \~10ms task will achieve >= 99.9% deduplication, and >= 95% for an extremely trivial task. Those ratios will succeed all day long:

```sh
#go test -count 1000 -race
PASS
ok      github.com/kofalt/go-memoize    28.878s

# go test -count 1000
PASS
ok      github.com/kofalt/go-memoize    15.830s

```

If this makes sense to you & I didn't miss anything, I will close this ticket & merge the branch.

**Comment by emad-elsaid** [comment]
- That makes sense. 
- How I ended up finding this issue it that I tried to solve the memorization myself in another package [here](https://github.com/emad-elsaid/memoize)
- This library memorization doesn't have this race condition 
- But also doesn't allow for serialization to external system or a file because it hold a pointer to functions
- So I was trying to find a way to have 2 level cache (in-flight functions, key->value map) in [this branch](https://github.com/emad-elsaid/memoize/tree/2lvlCache) 
- But then I faced the same issue I described here. So I wrote a test for your package to test if it has the same issue. because if not I can learn how the problem was solved in your solution.
- So either I get 100% deduplication without serializable cache
- Or high probability of deduplication with serialization cache 
- I'm trying to solve it, but I guess I'm working against the go memory model. as it specifies read/writes guaranteed serialization needs a synchronization mechanism like mutex/channel. and I'm trying to avoid that.
- Your description satisfied the issue I raised and it's ok if it's enough for the goal of this package.
- However I'll try to solve it in [here](https://github.com/emad-elsaid/memoize/tree/2lvlCache) somehow. 

I'll close this issue. and thanks for the unit tests and the note in README. that helps at least set the expectation for the package users.

**Comment by emad-elsaid** [comment]
It took me couple days to get a proper solution. I had to find a way to synchronize access to the same key concurrently 

and ended up having 2 different solution, one that memoize without explicit cache and another with it. 
The first guarantee duplicate call supression even in high concurrency environment.  and 0 allocations. 

The second guarantee the duplication supression but not the 0 allocation.

So the first can be used when you need a fast but forever caching. and the second when you need the flexibility to pass a cache and you don't mind a little overhead

Is it ok If I asked you to check the solution and tell me your opinion. given you have a context I would appreciate it if you would 
https://github.com/emad-elsaid/memoize
